name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Версия релиза"
        required: true

env:
  REGISTRY: cr.yandex/${{secrets.CR_ID}}/app
  RELEASE_VERSION: ${{ github.event.inputs.release_version }}
  IMAGE_TAG: ${{github.event.inputs.release_version}}_latest
  IMAGE: cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH 

      - name: Authenticate with Yandex Cloud
        run: |
          echo '${{secrets.YC_SA_JSON}}' > key.json
          yc config set service-account-key key.json
          yc config set cloud-id ${{secrets.YC_CLOUD_ID}}
          yc config set folder-id ${{secrets.YC_FOLDER_ID}}

      - name: Check if image with tag exists
        run: |
          EXISTS=$(yc container image list \
            --repository-name "app" \
            --format json | jq -r '.[].tags[]' | grep -Fx "${{ env.IMAGE_TAG }}" || true)

          if [ -z "$EXISTS" ]; then
            echo "::error::Image ${{ env.IMAGE }} does not exist in Container Registry"
            exit 1
          else
            echo "Image ${{ env.IMAGE }} exists"
          fi

      - name: CleanUp
        if: always()
        run: rm -f key.json